pipeline {
    agent { docker { image 'python:3' } }
    stages {
        stage("checkout") {
            steps {
                git branch: 'main',
                    url: 'https://github.com/bhuvana-baskaran/github-actions'
            }
        }
        stage("run python app") {
            steps {
                sh 'python3 src/addition.py'
            }
        }
    }
}
