pipeline {
    agent { docker { image 'python:3' } }
    stages {
        stage("checkout") {
            steps {
                checkout scm
            }
        }
        stage("run python app") {
            steps {
                sh 'python3 src/addition.py'
            }
        }
    }
}
